package org.klozevitz.enities.users.enums.views;

public enum CompanyView implements IBotView {
    // TODO проверить
    NULL_COMPANY_STATE_NOTIFICATION_VIEW,
    UNREGISTERED_WELCOME_VIEW,
    EMAIL_REQUEST_VIEW,
    EMAIL_CONFIRMATION_REQUEST_VIEW,
    // TODO проверить
    EMAIL_CONFIRMATION_NOTIFICATION_VIEW,
    WELCOME_VIEW,
    DEPARTMENTS_MANAGEMENT_VIEW,
    DEPARTMENT_TELEGRAM_USER_ID_REQUEST_VIEW,
    NEW_DEPARTMENT_REGISTRATION_NOTIFICATION_VIEW;
}